{{- if .Values.secrets.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "typesense.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secrets.externalSecret.storeName }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ .Values.secrets.secretName | default (printf "%s-secret" (include "typesense.fullname" .)) }}
  dataFrom:
    - extract:
        key: {{ .Values.secrets.externalSecret.extractKey }}
{{- end }}
