{{- if .Values.ingress.enabled -}}
{{- $fullName := include "typesense.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $pathPrefix := .Values.ingress.prefix -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
{{- with .Values.ingress -}}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .className }}
  ingressClassName: {{ .className }}
  {{- end }}
  tls:
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ $fullName }}-tls
  rules:
    {{- range .hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $pathPrefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-svc
                port:
                  number: {{ $svcPort }}
    {{- end }}
{{- end -}}
{{- end }}
